INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "center_crop", "normalize"]

DATASET:
  NAME: "OfficeHome"
  #  SOURCE_DOMAINS: ["art"]
  #  SOURCE_DOMAINS: ["clipart"]
  #  SOURCE_DOMAINS: ["product"]
  SOURCE_DOMAINS: ["Real_World"]

  #  TARGET_DOMAINS: ["art"]
  #  TARGET_DOMAINS: ["clipart"]
  #  TARGET_DOMAINS: ["product"]
  TARGET_DOMAINS: ["Real_World"]
# you can modify the code to explore four domains

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"
